version: '3.3'

services:

  db:
    image: mongo
    container_name: mongo
    logging:
      driver: none
    
    ports:
      - "27017:27017"

    restart: always

    volumes:
     # - /Users/snowman/ejemplo-docker/app/etc:/etc/mongo
      - /Users/snowman/practica1/mongodata:/data/db

    networks:
      - practica1-sopes

  backend:
    image: solaresjuan98/backend_p1_201800496
    #build: ./mongo-backend
    container_name: backend_p1_201800496

    ports: 
    - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - practica1-sopes

  frontend:
     image: solaresjuan98/frontend_p1_201800496
     container_name: frontend_p1_201800496
     ports:
       - "3000:3000"
     restart: always
     depends_on:
      - backend
     networks:
      - practica1-sopes

networks:
  practica1-sopes:
    #name: "practica1-sopes"
    driver: bridge